services:

  frontend:
    image: matheuspieropan/proposta-web
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - analisecredito-network

  postgres:
    image: postgres:16
    container_name: propostadb
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER: ${PROPOSTA_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${PROPOSTA_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - analisecredito-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - analisecredito-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - analisecredito-network

networks:
  analisecredito-network:
    driver: bridge